### ISSUE TITLE
Remove discouragement of jqueryPluginCommonjs.js

### ISSUE THREAD

**Issue by fluidblue** [umdjs/umd#23]
With CommonJS being used not only in node.js but also in browser environments, such as [browserify](http://browserify.org/) and [webmake](https://github.com/medikoo/modules-webmake), the discouragement [1] of jqueryPluginCommonjs.js should be removed (concerns Readme.md and jqueryPluginCommonjs.js itself).

[1] "However, jQuery is unlikely to run in most CommonJS environments, so only use this version if you know you are targeting a CommonJS environment that can load jQuery appropriately."

    // It is unlikely jQuery will run in a CommonJS
    // environment. See jqueryPlugin.js if you do
    // not want to add the extra CommonJS detection.

**Comment by EvanCarroll** [comment]
I think you guys misunderstood why the error was there. It had nothing to do with CommonJS and everything to do with the global `window` object. jQuery currently returns a factory itself if there is no window object. that means that all our UMD shit is borked under something like Node.js (where there is no `window` object) because jQuery is returning a factory itself and we're ignorant to this in our UMD wrapper.

**Comment by EvanCarroll** [comment]
So what I've done is seperate this bug report into two separate issues..

1. Removal of jqueryPluginCommonjs.js entirely -- not just the comment. Merge the one if-branch into jqueryPlugin.js. No comment or caveat about CommonJS in the new file: 
 https://github.com/umdjs/umd/issues/69
2. How do we better accommodate CommonJS: https://github.com/umdjs/umd/issues/68

Please advise.. Do those separate issue satisfy those on this report?

**Comment by EvanCarroll** [comment]
I'm closing out this issue because we know longer have two files, one of which to discourage. :+1:  Thanks for the input! Tell me what you think.
