### ISSUE TITLE
Check for CommonJS before AMD

### ISSUE THREAD

**Issue by aldendaniels** [umdjs/umd#59]
**Scenario**
 1. I'm building an embeddable widget using Browserify.
 2. Some client sites already have RequireJS loaded on the page, so `define()` is defined
 3. Some of my CommonJS dependencies use UMD
 4. So... these UMD dependencies suddenly can't be resolved since the UMD wrapper decides that this is an AMD context.

**Solution**
I think the solution is pretty simple - simply check for `module.exports` before checking for `define`. Browserify - unlike RequireJS - doesn't need to pollute the global namespace so the likelihood of `module` and `exports` being globally defined is low.

Thoughts?

**Comment by jrburke** [comment]
This normally is not a problem -- I thought the browserified bundles were generated wrapped in a closure with var define set to undefined if I recall correctly, so that anything in the browserified bundle should be self-contained. Maybe that is the "standalone" option in the browserify options?

Maybe diving more into how the bundle is generated might give more insight to the issue.

**Comment by aldendaniels** [comment]
Hey @jrburke - 

That's right - Browserify builds are self-contained. AMD loaders, by contrast, tend to define `window.define` and `window.require` in order to support async loading.

In my scenario (please re-read the "scenario" portion) - I'm using Browserify to bundle all dependencies into a single self-contained script. Some of my dependencies are use the UMD format.

The UMD code currently checks for AMD before CommonJS:

```javascript
if (typeof define === 'function' && define.amd) {
    define(['b'], factory);
} else if (typeof exports === 'object') {
    module.exports = factory(require('b'));
}
```

Because `define` and `define.amd` are defined on the `window` object on client sites, the AMD test is positive event though this code is part of a Browserify bundle. Oops! 

The fix is to simply switch the order of the tests:
```javascript
if (typeof exports === 'object') {
    module.exports = factory(require('b'));
} else if (typeof define === 'function' && define.amd) {
    define(['b'], factory);
}
```

Problem solved! Since Browserify builds are self-contained, `module` and `module.exports` shouldn't be globally defined so the reverse problem (loading CommonJS when you want AMD) is unlikely to occur.

Make sense?

**Comment by jrburke** [comment]
Sorry, I was a bit rushed in posting before: I was trying to indicate that any build tool that collects a bunch of modules that can have UMD forms need to adequately seal the environment, since they cannot guarantee the order in which a module may test for module environments.

If a user using AMD builds with r.js optimizer and [almond](https://github.com/jrburke/almond) for a set of self-contained modules, almond defines a local define for that set, it is not using the global one.

While it is true that usually AMD module systems do have a global define/require set up, it is not a guarantee that they are, just more likely.

Similar to the bundled AMD build case which encapsulates the AMD/CJS module APIs in a closure, I am pretty sure browserify also has an option for that, so I was trying figure out how we can solve the problem you had, since changing the suggestions here will not lead to fixing the problem you observed. The suggestions in this repo are just suggestions.

So if this issue is about figuring out the best way to use browserify to make sure this problem does not occur, we can do that. If you just feel like the AMD definitions should come second in this repo of suggestions, I'll let other contributors to this repo decide on that. I do not believe it will solve the issue though as module bundlers need to be aware of both formats since modules are authored by a wide range of people, and so a range of UMD-type module detection blocks.

**Comment by aldendaniels** [comment]
@jrburke - Thanks for your detailed reply! Sorry for delaying in getting back.

Your suggestion that Browserify redefine `define` within its bundled closurescope makes excellent sense. The Browserify documentation is unfortunately lacking on this point, but it looks like Browserify's `--standalone` option enables this "sealing" by adding the following inside a wrapping closure:

```javascript
var define, module, exports;
```

That will solve my problem. I've added a comment https://github.com/substack/node-browserify/issues/1073 proposing that this behavior be enabled by default.

While I still think that checking for CommonJS before AMD is a safter default, I agree that sealing the module bundle is needed regardless.

**Comment by thgreasi** [comment]
+1 This is how [mozilla/localForage](https://github.com/mozilla/localForage) does it as well.

**Comment by HQidea** [comment]
@jrburke - There is another reason to do so because webpack hacks AMD codes into CommonJS. Despite the performance costs of transformation, present order makes it difficult to detect weather the environment is using AMD or CommonJS for further function.

**Comment by jrburke** [comment]
@HQidea my [previous comment](https://github.com/umdjs/umd/issues/59#issuecomment-94831226) applies for webpack too. There are other owners for this repo that can manage an ordering pull request, but it is not something I want to spend time on.

**Comment by EvanCarroll** [comment]
Ok.. so background.. This is how it used to be, in fact here is the [patch that changed the order.](https://github.com/umdjs/umd/commit/992cc0d071b7ebcd7feaad2a5349bdbeab09a0fe)

And, this blog [ran into the problem that caused this..](https://github.com/umdjs/umd/commit/992cc0d071b7ebcd7feaad2a5349bdbeab09a0fe)

```text
Update: @BlaineBublitz pointed out the above UMD wrapper is incorrect as the AMD build tools will expose exports as an object. Thus we should check for AMD first for the above to actually work.

The funny thing is, I copied the above UMD example directly from https://github.com/umdjs/umd. I don't want this post to rag on UMD because UMD has very good intentions. But it kind of drives the point home that even UMD's own examples are incorrect.

Update 2: Kudos to @BlaineBublitz for sending a pull request and fixing this issue: https://github.com/umdjs/umd/commit/992cc0d071b7ebcd7feaad2a5349bdbeab09a0fe
```

So just focusing on this

> Update: @BlaineBublitz pointed out the above UMD wrapper is incorrect as the AMD build tools will expose exports as an object. Thus we should check for AMD first for the above to actually work.

It's at odds with your statement

> I think the solution is pretty simple - simply check for module.exports before checking for define. Browserify - unlike RequireJS - doesn't need to pollute the global namespace so the likelihood of module and exports being globally defined is low.

Turns out that AMD build tolls expose exports as an object which would throw this into CommonJS mode. What say you?

**Comment by EvanCarroll** [comment]
Ok, researching this further, it looks like one template has a fix [`nodeAdapter.js`](https://github.com/EvanCarroll/umd/blob/7a6b2174c8e3e5c942208f43f3de76ac2e7a2ea7/nodeAdapter.js#L20)

    typeof module === 'object' && module.exports && typeof define !== 'function' ?


@aldendaniels said,

> That's right - Browserify builds are self-contained. AMD loaders, by contrast, tend to define window.define and window.require in order to support async loading.

So it makes me wonder if whatever problem you're experiencing could be alleviated with making CommonJS's test first, and adding that condition that `typeof define !== 'function'`. Is there any case where we want CommonJS behavior and `typeof define == 'function'`?

I'm just brute forcing this and auditing. Please give some input guys.

**Comment by EvanCarroll** [comment]
I'm going to close this. Feel free to reopen it with response.

**Comment by vernak2539** [comment]
Hello, we are running into this problem as well. With the rise of webpack, which understands all module types under the sun, we are running into the problem where the ordering of the `define` and `module.exports` matters. 

We have tested it with webpack, and switching the order to check for CJS first includes our module as we'd expect. If this order is not changed we then have to alias all the paths in our libraries because webpack doesn't use the same path system as requirejs. 

I feel this is a reason to change the UMD templates
